server:
  port: 8292
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/samFernando77/spring-cloud-config-store
          search-paths:
           - '*service'



